api_key: ''
llm_model: ollama
base_url: https://isa-impendent-keyla.ngrok-free.dev
llm_model_name: qwen2.5-14b-finetuned
embedding_models: maidalun1020/bce-embedding-base_v1
embedding_type: local
context_length: 1200000
embedding_url: ''
rerank_model: maidalun1020/bce-reranker-base_v1
temperature: 0.5
history_len: 5
timeout: 600
proxies: {}
